/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package anagramchecker;

public class App {

    public static void main(String[] args) {
        if(args.length != 2){
            System.out.println("This program expects two input parameters for checking for anagrams!");
        }
        var isAnagram = AnagramChecker.isAnagram(args[0], args[1]);

        if(isAnagram){
            System.out.printf("String %s and %s are anagrams of one another%n", args[0], args[1]);
        }else{
            System.out.printf("String %s and %s aren't anagrams.", args[0], args[1]);
        }
    }
}
